export type Signal = "leadership"|"ma"|"news"|"transformation"|"partnerships"|"funding"|"product"|"expansion"|"procurement"|"hiring"|"restructuring"|"regulatory";
export type Development={type:Signal;date:string;title:string;summary:string;source:{name:string;url:string;published_date?:string};evidence:string;confidence:number;gtm_relevance:string;related_signals:string[]};
export type CompanyResult={company:string;domain?:string|null;research_window_from:string;research_window_to:string;developments:Development[];sources_scanned:number;source_urls:string[];warnings:string[];status:string};
export type ResearchJob={job_id:string;status:"queued"|"running"|"complete"|"failed";result?:CompanyResult;batch_result?:{results:CompanyResult[]};error?:string};
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";

async function readJson(r:Response){if(!r.ok)throw new Error(await r.text());return r.json()}
export async function startResearch(company:string,lookback_months:number,research_types:Signal[]):Promise<ResearchJob>{const r=await fetch(`${API}/research`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({company:"",company_website:company,lookback_months,research_types})});return readJson(r)}
export async function startResearchCsv(file:File,lookback_months:number,research_types:Signal[]):Promise<ResearchJob>{const fd=new FormData();fd.append("file",file);fd.append("lookback_months",String(lookback_months));fd.append("research_types",research_types.join(","));const r=await fetch(`${API}/research/csv`,{method:"POST",body:fd});return readJson(r)}
export async function getResearch(jobId:string):Promise<ResearchJob>{const r=await fetch(`${API}/research/${jobId}`,{cache:"no-store"});return readJson(r)}
export function csvBlob(rows:CompanyResult[]){const esc=(v:string)=>`"${String(v).replaceAll('"','""')}"`;const lines=[["company","domain","development_type","date","title","summary","source","source_url","evidence","confidence","gtm_relevance"],...rows.flatMap(r=>r.developments.map(d=>[r.company,r.domain||"",d.type,d.date,d.title,d.summary,d.source.name,d.source.url,d.evidence,String(d.confidence),d.gtm_relevance]))];return new Blob([lines.map(x=>x.map(esc).join(",")).join("\n")],{type:"text/csv;charset=utf-8"})}
